ARG DZMAP_IMAGE=ghcr.io/woozymasta/dzmap
ARG DZMAP_TAG=latest

FROM $DZMAP_IMAGE:$DZMAP_TAG
ENV ZOOM_LIMIT=6
RUN ["/bin/loader", "--log-level=trace", "--limit=chernarusplus", "--limit=enoch", "--limit=sakhal"]
